name: Run kubectl commands via AWS SSM

on:
  workflow_dispatch:
    inputs:
      jump_host_instance_id:
        description: 'ID of the Jump Host EC2 instance'
        required: true
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
      commands:
        description: 'List of kubectl commands to run'
        required: true

jobs:
  run-kubectl-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Run kubectl commands via AWS SSM
      run: |
        # Set AWS credentials for this job
        export AWS_ACCESS_KEY_ID="${{ github.event.inputs.aws_access_key_id }}"
        export AWS_SECRET_ACCESS_KEY="${{ github.event.inputs.aws_secret_access_key }}"
        export AWS_DEFAULT_REGION="${{ github.event.inputs.aws_region }}"

        # Start AWS SSM session
        session_id=$(aws ssm start-session --target ${{ github.event.inputs.jump_host_instance_id }} --document-name AWS-StartInteractiveCommand --parameters "command=${{ github.event.inputs.commands }}" --query "SessionId" --output text)

        # Wait for SSM session to complete
        aws ssm wait session-terminated --session-id $session_id
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
