name: Commit Message Linter

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit range
        id: commit_range
        run: |
          # Get the range of commits for this push
          before_sha="${{ github.event.before }}"
          after_sha="${{ github.sha }}"

          # In case this is the first commit on a branch (before will be all zeroes), only check the latest commit
          if [ "$before_sha" = "0000000000000000000000000000000000000000" ]; then
            echo "::set-output name=commit_range::${after_sha}"
          else
            echo "::set-output name=commit_range::${before_sha}..${after_sha}"
          fi

      - name: Check commit messages
        run: |
          # Get the commit messages in the given range
          commit_messages=$(git log --format=%B ${{ steps.commit_range.outputs.commit_range }})

          # Check for 'RC-*' pattern in commit messages
          if ! echo "$commit_messages" | grep -q 'RC-'; then
            echo "❌ Commit message does not contain 'RC-*' pattern"
            exit 1
          fi

      - name: Success message
        if: success()
        run: echo "✅ Commit message contains 'RC-*'"
