name: Commit Message Linter

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check commit message
        run: |
          # Retrieve the commit message of the latest commit
          commit_message=$(git show -s --format=%s)

          # Check for 'RC-*' pattern in the commit message
          if ! echo "$commit_message" | grep -q 'RC-'; then
            echo "❌ Commit message does not contain 'RC-*' pattern"
            exit 1
          fi

      - name: Success message
        if: success()
        run: echo "✅ Commit message contains 'RC-*'"
