name: Run kubectl commands via AWS SSM

on:
  workflow_dispatch:
    inputs:
      jump_host_instance_id:
        description: 'ID of the Jump Host EC2 instance'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
      commands:
        description: 'List of kubectl commands to run'
        required: true

jobs:
  run-kubectl-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ github.event.inputs.aws_region }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ github.event.inputs.aws_region }}

    - name: Run kubectl commands via AWS SSM
      run: |
        # Start AWS SSM session
        session_id=$(aws ssm start-session --target ${{ github.event.inputs.jump_host_instance_id }} --document-name AWS-StartInteractiveCommand --parameters "command=${{ github.event.inputs.commands }}" --query "SessionId" --output text)

        # Wait for SSM session to complete
        aws ssm wait session-terminated --session-id $session_id
